import { isToolUIPart, type UIMessage } from "ai";
import type { ModelEntry } from "../models/types";

type Part = UIMessage["parts"][number];

/** Text that replaces an image part when the target model cannot take image input (ADR-7). */
export const IMAGE_OMITTED_TEXT = "[画像は省略されました]";

const PROVIDER_FIELDS = [
	"providerMetadata",
	"providerReference",
	"callProviderMetadata",
	"resultProviderMetadata",
] as const;

/** Tool states that never reached a result; providers reject a call without its result. */
const INCOMPLETE_TOOL_STATES: ReadonlySet<string> = new Set(["input-streaming", "input-available"]);

/**
 * The provider that generated an assistant message, read from its `ResponseMetadata.provider`.
 * User and system parts have no generating provider, so anything provider-specific on them is
 * client-supplied and is always stripped.
 */
function originProvider(message: UIMessage): string | undefined {
	if (message.role !== "assistant") return undefined;
	const { metadata } = message;
	if (typeof metadata !== "object" || metadata === null) return undefined;
	const provider = (metadata as { readonly provider?: unknown }).provider;
	return typeof provider === "string" ? provider : undefined;
}

function isImage(mediaType: string): boolean {
	return mediaType === "image" || mediaType.startsWith("image/");
}

function withoutProviderFields(part: Part): Part {
	const copy: Record<string, unknown> = { ...part };
	for (const field of PROVIDER_FIELDS) delete copy[field];
	return copy as Part;
}

interface PartContext {
	readonly target: ModelEntry;
	readonly sameProvider: boolean;
}

/** Returns the adapted copy of `part`, or `undefined` when the part must not be sent. */
function adaptPart(part: Part, { target, sameProvider }: PartContext): Part | undefined {
	const copy = sameProvider ? { ...part } : withoutProviderFields(part);

	switch (part.type) {
		case "reasoning":
		case "reasoning-file":
			// Reasoning (and its signature in providerMetadata) is only valid for the provider that
			// produced it, and only useful to a model that reasons.
			return sameProvider && target.capabilities.reasoning ? copy : undefined;
		case "custom":
			return sameProvider ? copy : undefined;
		case "file":
			if (isImage(part.mediaType) && !target.capabilities.imageInput) {
				return { type: "text", text: IMAGE_OMITTED_TEXT };
			}
			return copy;
		default:
			if (isToolUIPart(part)) {
				if (INCOMPLETE_TOOL_STATES.has(part.state)) return undefined;
				if (part.providerExecuted === true && !sameProvider) return undefined;
			}
			return copy;
	}
}

/**
 * Adapts a UI history for the model that will answer the next turn (Req 3.3, ADR-7).
 *
 * Applied on the server right before `convertToModelMessages`, so the learner's displayed history
 * keeps everything. Reasoning, provider metadata and provider-specific parts survive only when
 * the message was generated by the target's provider; images become a text placeholder for a
 * model without image input; tool calls without a result are dropped. A message left with no
 * sendable part is dropped. The input is never mutated: messages and parts are shallow copies,
 * nested values (tool input/output, data payloads) are shared and must be treated as read-only.
 */
export function adaptHistoryForModel(
	messages: readonly UIMessage[],
	target: ModelEntry,
): UIMessage[] {
	const adapted: UIMessage[] = [];
	for (const message of messages) {
		const context: PartContext = {
			target,
			sameProvider: originProvider(message) === target.provider,
		};
		const parts = message.parts.flatMap((part) => adaptPart(part, context) ?? []);
		if (parts.every((part) => part.type === "step-start")) continue;
		adapted.push({ ...message, parts });
	}
	return adapted;
}
